openapi: '3.0.0'

info:
  title: BOMS API
  description: BOMS API Specification
  version: "0.1.1"

servers:
  - url: localhost:8080
    description: test server

paths:
  /projects:
    get:
      description: 返回项目列表
      responses:
        '200':
          description: success
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Project'
                example:
                  - id: 101
                    name: 广东风电
                  - id: 102
                    name: 国网财务分析
    post:
      description: 新建项目
      requestBody:
        description: 项目信息
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Project'
            example:
              $ref: '#/components/examples/project'
      responses:
        '201':
          description: 创建项目成功
          
  /projects/{id}:
    get:
      description: 读取项目内容
      parameters:
        - in: path
          name: id
          description: 项目ID
          schema:
            type: string
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BOI'
              example:
                raw: {}
                mdl: {}
                prop: {}
                con: {}
        '404':
          description: 项目不存在
          
    put:
      description: 更新项目内容
      parameters:
        - in: path
          name: id
          description: 项目ID
          schema:
            type: string
          required: true
      requestBody:
        description: 项目内容
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/BOI'
            example:
              raw: {}
              mdl: {}
              prop: {}
              con: {}
      responses:
        '200':
          description: success
    delete:
      description: Deletes a project
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Project deleted
        '404':
          description: Project not found
  /projects/{id}/dataobj:
    put:
      description: 发布业务对象
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 发布业务对象成功
        '404':
          description: 项目不存在
      

components:
  examples:
    project:
      value:
        id: 123
        name: '广东风电'
      summary: A demo project

  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
        
    BOI:
      type: object
      properties:
        raw:
          type: object
        mdl:
          type: object
        prop:
          type: object
        con:
          type: object
      required:
        - raw
        - mdl
        - prop
        - con
